export GUROBI_HOME="/opt/gurobi701/linux64/"
export PATH="${PATH}:${GUROBI_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
export GRB_LICENSE_FILE="/home/ubuntu/gurobi.lic"
export LD_LIBRARY_PATH_SCREEN="${LD_LIBRARY_PATH}"